// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCDvK9Gmfa0yglv7IRMWGfQAyp92EZcJg',
    appId: '1:235600157985:web:dd3d24618ae3d79351f260',
    messagingSenderId: '235600157985',
    projectId: 'chat-app-aaf4c',
    authDomain: 'chat-app-aaf4c.firebaseapp.com',
    storageBucket: 'chat-app-aaf4c.firebasestorage.app',
    measurementId: 'G-VMPSXZHFT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAahGufwS9ygQWQ6U2wvCgJfyX_VCpJyoQ',
    appId: '1:235600157985:android:a37322090d148b5d51f260',
    messagingSenderId: '235600157985',
    projectId: 'chat-app-aaf4c',
    storageBucket: 'chat-app-aaf4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yqLgNnNYszUPg1Kmjnu-LSeZLCh3mxw',
    appId: '1:235600157985:ios:b337c73db0f170cc51f260',
    messagingSenderId: '235600157985',
    projectId: 'chat-app-aaf4c',
    storageBucket: 'chat-app-aaf4c.firebasestorage.app',
    iosBundleId: 'com.example.realChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yqLgNnNYszUPg1Kmjnu-LSeZLCh3mxw',
    appId: '1:235600157985:ios:b337c73db0f170cc51f260',
    messagingSenderId: '235600157985',
    projectId: 'chat-app-aaf4c',
    storageBucket: 'chat-app-aaf4c.firebasestorage.app',
    iosBundleId: 'com.example.realChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCDvK9Gmfa0yglv7IRMWGfQAyp92EZcJg',
    appId: '1:235600157985:web:45269426779afdf351f260',
    messagingSenderId: '235600157985',
    projectId: 'chat-app-aaf4c',
    authDomain: 'chat-app-aaf4c.firebaseapp.com',
    storageBucket: 'chat-app-aaf4c.firebasestorage.app',
    measurementId: 'G-K93P20CR74',
  );
}
